spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
app:
  topic:
    text: text
    cost: cost
  kafka:
    bootstrap-servers: kafka1:9092,kafka2:9092,kafka3:9092

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.birse: DEBUG