spring:
  jackson:
    serialization:
      write_dates_as_timestamps: false
app:
  topic:
    text: text
    cost: cost

logging:
  level:
    root: WARN
    org.springframework.web: INFO
    com.birse: DEBUG